AWSTemplateFormatVersion: '2010-09-09'
Description: 'Portfolio Insight Site - Creates S3, Lambda, IAM, DynamoDB, and API Gateway resources using free tier'

Parameters:
  ProjectName:
    Type: String
    Default: portfolio-insight
    Description: Name for the project resources
    
  DeploymentBucket:
    Type: String
    Description: S3 bucket where Lambda code is uploaded
    
  LambdaCodeKey:
    Type: String
    Description: S3 key for the Lambda code zip file

Resources:
  DynamoDBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${DeploymentBucket}.s3.amazonaws.com/templates/dynamodb.yml'
      Parameters:
        ProjectName: !Ref ProjectName

  LambdaStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - DynamoDBStack
    Properties:
      TemplateURL: !Sub 'https://${DeploymentBucket}.s3.amazonaws.com/templates/lambda.yml'
      Parameters:
        ProjectName: !Ref ProjectName
        DeploymentBucket: !Ref DeploymentBucket
        LambdaCodeKey: !Ref LambdaCodeKey

  ApiGatewayStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - LambdaStack
    Properties:
      TemplateURL: !Sub 'https://${DeploymentBucket}.s3.amazonaws.com/templates/apigateway.yml'
      Parameters:
        ProjectName: !Ref ProjectName

Outputs:
  # S3 相關輸出已被移除，因為使用手動創建的儲存桶
  # 如果需要 S3 儲存桶信息，請直接使用 AWS 控制台或 CLI 獲取

  PortfolioTableName:
    Description: Name of the main DynamoDB table
    Value: !GetAtt DynamoDBStack.Outputs.PortfolioTableName
    
  ProjectViewsTableName:
    Description: Name of the Project Views DynamoDB table
    Value: !GetAtt DynamoDBStack.Outputs.ProjectViewsTableName

  LambdaFunctionName:
    Description: Name of the Lambda function
    Value: !GetAtt LambdaStack.Outputs.LambdaFunctionName

  ApiEndpoint:
    Description: URL for the API Gateway endpoint
    Value: !GetAtt ApiGatewayStack.Outputs.ApiEndpoint